### ISSUE TITLE
 Implement Hero Section Component

### ISSUE THREAD

**Issue by medetcandiler** [202303-PRM-TR-FEW/crowdfunding-app-team-9#1]
Description:
Create a responsive Hero Section component based on the design provided in Figma. The section should adapt to different screen sizes and maintain a visually appealing layout.

Tasks:
- [x] Write JSX structure and CSS styles for the Hero Section component.
- [x] Make the "Start Today" button clickable and link it to the "/starttoday" path.

Design Reference: [Design link](https://app.uizard.io/templates/8oJJGXYj4yCWAoe9Jj9A/overview)

Additional Notes:
- Ensure that the Hero Section component is responsive and displays correctly on various devices.
- Test the functionality of the "Start Today" button to ensure it correctly navigates to the "/starttoday" page.

**Comment by bohemianmir** [comment]
I wrote JSX structure and CSS
I made the button clickable and linked it to the page which I will be working on on my next issue
