### ISSUE TITLE
Implement 'My Projects' Page Component

### ISSUE THREAD

**Issue by gurkanyigitgr** [202303-PRM-TR-FEW/crowdfunding-app-team-9#32]
Being faithful to our exemplary **design**;

1. On the left side, there will be details such as the photo of the project, title, progressbar.
2.  On the right side, there will be the 'transaction history' section and below it the sort dropdown button within all projects. Below these, a 'view more' button will be added.
3. At the bottom of the right-hand div, there will be a 'statics' component.

**Comment by medetcandiler** [comment]
Hey @gurkanyigitgr ,

For development purposes, I've created a placeholder array of donation objects. This array can be used to simulate and manipulate donor data in our crowdfunding app. Feel free to leverage this placeholder array to test and showcase the functionality related to donor information.

Please note that these donation objects are placeholders and don't represent real donor data. They are designed to help us develop and fine-tune features related to donors and donations. 

You can find the placeholder donation array below:

```javascript
const placeholderDonations = [
  {
    id: 1,
    projectId: 1,
    donorName: "John Smith",
    amount: 100,
    avatar: "https://via.placeholder.com/150/FF7F50/FFFFFF?text=JS",
    comment: "Great cause! Happy to contribute.",
  },
  {
    id: 2,
    projectId: 1,
    donorName: "Jane Doe",
    amount: 50,
    avatar: "https://via.placeholder.com/150/FF7F50/FFFFFF?text=JD",
    comment: "Wishing you all the best with the project.",
  },
  {
    id: 3,
    projectId: 1,
    donorName: "Michael Johnson",
    amount: 200,
    avatar: "https://via.placeholder.com/150/FF7F50/FFFFFF?text=MJ",
    comment: "Happy to support such a meaningful initiative.",
  },
  {
    id: 4,
    projectId: 1,
    donorName: "Sarah Thompson",
    amount: 150,
    avatar: "https://via.placeholder.com/150/FF7F50/FFFFFF?text=ST",
    comment: "For the love of animals!",
  },
  {
    id: 5,
    projectId: 1,
    donorName: "David Wilson",
    amount: 75,
    avatar: "https://via.placeholder.com/150/FF7F50/FFFFFF?text=DW",
    comment: "Inspired by your project. Keep up the good work.",
  },
  {
    id: 6,
    projectId: 1,
    donorName: "Emily Davis",
    amount: 120,
    avatar: "https://via.placeholder.com/150/FF7F50/FFFFFF?text=ED",
    comment: "This cause is close to my heart. Best of luck!",
  },
];
